package rules;
dialect  "mvel"

import timejts.SIEMCentre.model.Log;
import timejts.SIEMCentre.model.RaisedAlarm;

query "Get new raised alarms"
    $a: RaisedAlarm(raised == false)
end

query "Get logs"
    $l: Log()
end

rule "Raise alarm"
    agenda-group "raise-alarm"
    when
        $a: RaisedAlarm(raised == false)
    then
        System.out.println(drools.getRule().getName());
        modify($a){
            setRaised(true)
        }
end
