package timejts.SIEMCentre.model;

public enum Facility {
    KERN, USER, MAIL, DAEMON, AUTH, SYSLOG, LPR, NEWS,
    UUCP, CLOCK_DAEMON, AUTHPRIV, FTP, NTP, LOGAUDIT, LOGALERT,
    CRON, LOCAL0, LOCAL1, LOCAL2, LOCAL3, LOCAL4, LOCAL5, LOCAL6, LOCAL7
}
